#!/usr/bin/env python3
"""Build a self-contained browser page for start × entity route audits."""
from __future__ import annotations
import argparse, json
from pathlib import Path

p=argparse.ArgumentParser();p.add_argument('--r0',type=Path,required=True);p.add_argument('--r20',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args()
data={'r0':json.loads(a.r0.read_text()),'r20':json.loads(a.r20.read_text())}
raw=json.dumps(data,ensure_ascii=False).replace('</script>','<\\/script>')
page='''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NavMem3D 路线组合审阅</title><style>
body{margin:0;background:#101317;color:#edf2f7;font:15px system-ui,sans-serif}main{max-width:1400px;margin:auto;padding:24px}.note{color:#b7c5d3;line-height:1.6}.stats{display:flex;gap:12px;flex-wrap:wrap}.card{background:#1a2027;border:1px solid #303842;border-radius:10px;padding:12px;margin:12px 0}select{background:#242d37;color:white;border:1px solid #536170;padding:7px;border-radius:6px}table{width:100%;border-collapse:collapse;margin-top:14px}td,th{padding:8px;border-bottom:1px solid #303842;text-align:left}.yes{color:#73e6a1}.no{color:#ff7d78}code{color:#97d6ff}
</style><main><h1>NavMem3D：全量起点 × 实体候选路线审阅</h1><p class="note">每个条目只使用 M 的三态图、拓扑起点和 B→M 实体候选。A* 只穿越 free；occupied 与 unknown 均禁行。这里检验可达性与路线长度，不把“可达”误当作实例识别或真实避障成功。</p><div id="stats" class="stats"></div><div class="card"><label>机器人半径：<select id="radius"><option value="r0">0 m（连通性）</option><option value="r20">0.2 m（安全余量）</option></select></label><label>类别：<select id="category"></select></label><table><thead><tr><th>实体实例</th><th>候选路线数</th><th>可达</th><th>可达率</th><th>平均路线长度</th></tr></thead><tbody id="rows"></tbody></table></div></main><script id="data" type="application/json">__DATA__</script><script>
const all=JSON.parse(document.querySelector('#data').textContent),radius=document.querySelector('#radius'),category=document.querySelector('#category'),stats=document.querySelector('#stats'),rows=document.querySelector('#rows');function draw(){const d=all[radius.value],cats=[...new Set(d.entity_summary.map(x=>x.category_id))].sort();category.innerHTML='<option value="">全部类别</option>'+cats.map(c=>`<option ${category.value===c?'selected':''}>${c}</option>`).join('');const pick=category.value?d.entity_summary.filter(x=>x.category_id===category.value):d.entity_summary;stats.innerHTML=`<div class="card">起点：${d.topology_start_count}</div><div class="card">实体：${d.entity_count}</div><div class="card">候选对：${d.candidate_route_pairs}</div><div class="card">可达：${d.reachable_pairs} / ${d.candidate_route_pairs} (${(d.reachability*100).toFixed(1)}%)</div>`;rows.innerHTML=pick.map(x=>`<tr><td><code>${x.entity_id}</code> · ${x.category_id}</td><td>${x.tested_pairs}</td><td class="${x.reachable_pairs===x.tested_pairs?'yes':'no'}">${x.reachable_pairs}</td><td>${(x.reachability*100).toFixed(1)}%</td><td>${x.mean_cost_m.toFixed(2)} m</td></tr>`).join('')};radius.onchange=draw;category.onchange=draw;draw();
</script>'''.replace('__DATA__',raw)
a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(page,encoding='utf-8');print(a.output)
